package com.robinsonduffy.guesswho;

public enum Person {
    AHSOKA_TANO,
    KIT_FISTO,
    GENERAL_GRIEVOUS,
    JABBA_THE_HUTT,
    EMPEROR_PALPATINE,
    AAYLA_SECURA,
    DARTH_MAUL,
    HAN_SOLO,
    CHEWBACCA,
    COUNT_DOOKU,
    ANAKIN_SKYWALKER,
    R2_D2,
    DARTH_VADER,
    MACE_WINDU,
    PADME_AMIDALA,
    PRINCESS_LEIA,
    OBI_WAN_KENOBI,
    ASAJJ_VENTRESS,
    YODA,
    CAPTAIN_REX,
    BOBA_FETT,
    C_3PO,
    WICKET_W_WARRICK,
    LUKE_SKYWALKER
}
